# Generated by Django 5.2.7 on 2025-11-12 19:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders_app', '0002_alter_order_offer_type_alter_order_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='features',
            field=models.JSONField(default=list),
        ),
    ]
