# Generated by Django 5.2.7 on 2025-11-07 08:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('offers_app', '0003_alter_offer_options_remove_offer_price_offerdetail'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='offer',
            name='delivery_time',
        ),
    ]
