# Generated by Django 5.2.7 on 2025-11-10 21:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('offers_app', '0006_alter_offerdetail_price'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='offer',
            options={'ordering': ['id']},
        ),
    ]
